In [3]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import r2_score

In [4]:
data=pd.read_csv("dataset.csv")
data

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,...,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.7150,87.917,4,acoustic
1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,...,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.2670,77.489,4,acoustic
2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,...,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.1200,76.332,4,acoustic
3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,...,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.1430,181.740,3,acoustic
4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,...,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.1670,119.949,4,acoustic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113995,113995,2C3TZjDRiAzdyViavDJ217,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Sleep My Little Boy,21,384999,False,0.172,0.2350,...,-16.393,1,0.0422,0.6400,0.928000,0.0863,0.0339,125.995,5,world-music
113996,113996,1hIz5L4IB9hN3WRYPOCGPw,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Water Into Light,22,385000,False,0.174,0.1170,...,-18.318,0,0.0401,0.9940,0.976000,0.1050,0.0350,85.239,4,world-music
113997,113997,6x8ZfSoqDjuNa5SVP5QjvX,Cesária Evora,Best Of,Miss Perfumado,22,271466,False,0.629,0.3290,...,-10.895,0,0.0420,0.8670,0.000000,0.0839,0.7430,132.378,4,world-music
113998,113998,2e6sXL2bYv4bSz6VTdnfLs,Michael W. Smith,Change Your World,Friends,41,283893,False,0.587,0.5060,...,-10.889,1,0.0297,0.3810,0.000000,0.2700,0.4130,135.960,4,world-music
113999,113999,2hETkH7cOfqmz3LqZDHZf5,Cesária Evora,Miss Perfumado,Barbincor,22,241826,False,0.526,0.4870,...,-10.204,0,0.0725,0.6810,0.000000,0.0893,0.7080,79.198,4,world-music

In [5]:
x=data[['danceability','energy']]#you should take multiple columns for more accuracy
x

        danceability  energy
0              0.676  0.4610
1              0.420  0.1660
2              0.438  0.3590
3              0.266  0.0596
4              0.618  0.4430
...              ...     ...
113995         0.172  0.2350
113996         0.174  0.1170
113997         0.629  0.3290
113998         0.587  0.5060
113999         0.526  0.4870

[114000 rows x 2 columns]

In [6]:
y=data['track_genre']
y

0            acoustic
1            acoustic
2            acoustic
3            acoustic
4            acoustic
             ...
113995    world-music
113996    world-music
113997    world-music
113998    world-music
113999    world-music
Name: track_genre, Length: 114000, dtype: object

In [7]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=43)

In [8]:
model=KNeighborsClassifier(n_neighbors=5)
model.fit(x_train,y_train)

KNeighborsClassifier()

In [9]:
danceability=float(input("Enter your dancebility values:"))
energy=float(input("Enter your energy values:"))
inputss=[[danceability,energy]]
print(model.predict(inputss))

Enter your dancebility values:0.333
Enter your energy values:0.456
['country']

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

In [11]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(
        model, x, y,scoring='accuracy'
    )
print("Average Accuracy =", scores.mean())

Average Accuracy = 0.041473684210526315

In [12]:
from sklearn.naive_bayes import MultinomialNB

In [13]:
data=pd.read_csv("combined_data.csv")
data

      label                                               text
0         1  ounce feather bowl hummingbird opec moment ala...
1         1  wulvob get your medircations online qnb ikud v...
2         0   computer connection from cnn com wednesday es...
3         1  university degree obtain a prosperous future m...
4         0  thanks for all your answers guys i know i shou...
...     ...                                                ...
3132      0  hi is there a way documented or not to extract...
3133      1  ridge similar ground grew enemy next saying si...
3134      1  this oil is a brand fresh topical lubricant\np...
3135      0  john w krahn writes tom allison wrote how do i...
3136      1  http agreeput hk viagra escapenumber pills x e...

[3137 rows x 2 columns]

In [14]:
text=data['text']

In [15]:
y=data['label']
y

0       1
1       1
2       0
3       1
4       0
       ..
3132    0
3133    1
3134    1
3135    0
3136    1
Name: label, Length: 3137, dtype: int64

In [16]:
from sklearn.preprocessing import LabelEncoder
label=LabelEncoder()
x=label.fit_transform(text)
x=np.array(x).reshape(-1,1)

In [17]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=40)

In [18]:
model=MultinomialNB()
model.fit(x_train,y_train)

MultinomialNB()

In [19]:
t=input("Enter your words:")
inputss=label.fit_transform([t])
q=np.array(inputss).reshape(-1,1)
print(model.predict(q))

Enter your words:hii dear
[1]